openapi: 3.0.0
info:
  version: 2.0.0
  title: DXI
paths:
  /topic:
    post:
      operationId: addNewTopic
      description: Adds new Topic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponse'
    get:
      operationId: getAllTopics
      description: Returns all topics
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicListResponse'
components:
  schemas:
    TopicRequest:
      type: object
      properties:
        topicName:
          type: string
        description:
          type: string
    TopicResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        topicName:
          type: string
        description:
          type: string
    TopicListResponse:
      type: array
      items:
        $ref: "#/components/schemas/TopicResponse"
