openapi: 3.0.0
info:
  version: 2.0.0
  title: DXI
paths:
  /topic:
    post:
      operationId: addNewTopic
      description: Adds new Topic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicPostRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicPostResponse'
    get:
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
            format: int64
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            format: int64
      operationId: getAllTopics
      description: Returns all topics
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicFindResponse'
components:
  schemas:
    TopicPostResponse:
      type: object
      properties:
        id:
          type: integer
        topicName:
          type: string
        description:
          type: string
    TopicPostRequest:
      type: object
      properties:
        topicName:
          type: string
        description:
          type: string
    TopicFindResponse:
      type: object
      properties:
        startElement:
          type: integer
          format: int64
        totalCount:
          type: integer
          format: int64
        count:
          type: integer
          format: int64
        results:
          type: array
          items:
            $ref: '#/components/schemas/Topic'
    Topic:
      type: object
      properties:
        id:
          type: integer
          format: int64
        topicName:
          type: string
        description:
          type: string
    TopicListResponse:
      type: array
      items:
        $ref: "#/components/schemas/TopicResponse"
