services:
  keycloak:
    depends_on:
      - postgresdb
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgresdb
      DB_DATABASE: management
      DB_USER: management
      DB_PASSWORD: management
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    image: jboss/keycloak
    ports:
      - "28080:8080"
    restart: unless-stopped

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=management
      - POSTGRES_USER=management
      - POSTGRES_PASSWORD=management
    ports:
      - 5432:5432