services:
  keycloak:
    depends_on:
      - keycloackDB
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloackDB
      DB_DATABASE: keycloack
      DB_USER: keycloack
      DB_PASSWORD: keycloack
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    image: jboss/keycloak
    ports:
      - "28080:8080"
    restart: unless-stopped

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=management
      - POSTGRES_USER=management
      - POSTGRES_PASSWORD=management
    ports:
      - 5432:5432
  keycloackDB:
    image: postgres
    environment:
      - POSTGRES_DB=keycloack
      - POSTGRES_USER=keycloack
      - POSTGRES_PASSWORD=keycloack
    ports:
      - 5433:5432