openapi: 3.0.0
info:
  version: 2.0.0
  title: DXI
paths:
  /import:
    get:
      operationId: noAction
      responses:
        '200':
          description: OK
components:
  schemas:
    ImportStudentsNotification:
      type: object
      properties:
        originalSourceName:
          type: string
        bucket:
          type: string
        exchangeFile:
          type: string

    ImportStudents:
      type: object
      properties:
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'
    Student:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
        albumNo:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        semesters:
          type: array
          items:
            $ref: '#/components/schemas/Semester'
    Semester:
      type: object
      properties:
        fieldOfStudy:
          type: string
        year:
          type: string
        semester:
          type: string
